# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

resources:         
  repositories:
  - repository: destinationRepo
    type: github
    name: andrebriggs/az-pipeline-yaml-dest
    endpoint: andrebriggs

steps:
- checkout: destinationRepo
  persistCredentials: true
  clean: true

- bash: pwd
